-- Insert verification questions with SHA-256 hashing
USE `portfolio`;

INSERT INTO verification_questions (QUESTION, ANSWER_HASH, PLACEHOLDER, DIFFICULTY, IS_ACTIVE) VALUES 
('Type the word ''discipline'' backwards', LOWER(SHA2('enilpicsid', 256)), 'e...', 1, 1),
('What is 12 + 7?', LOWER(SHA2('19', 256)), 'Answer', 1, 1),
('What is the opposite of ''Night''?', LOWER(SHA2('day', 256)), 'd...', 1, 1),
('Type the first 4 letters of the day name ''Monday''', LOWER(SHA2('mond', 256)), 'm...', 1, 1),
('Type the first 4 letters of the day name ''Tuesday''', LOWER(SHA2('tues', 256)), 't...', 1, 1),
('Type the first 4 letters of the day name ''Wednesday''', LOWER(SHA2('wedn', 256)), 'w...', 1, 1),
('What is 15 - 6?', LOWER(SHA2('9', 256)), 'Answer', 1, 1),
('Type ''FOCUS'' in all lowercase', LOWER(SHA2('focus', 256)), 'f...', 1, 1),
('What is 5 + 8?', LOWER(SHA2('13', 256)), 'Answer', 1, 1),
('What is 20 - 7?', LOWER(SHA2('13', 256)), 'Answer', 1, 1),
('What is 9 + 6?', LOWER(SHA2('15', 256)), 'Answer', 1, 1),
('What is 18 - 9?', LOWER(SHA2('9', 256)), 'Answer', 1, 1),
('What is 7 × 2?', LOWER(SHA2('14', 256)), 'Answer', 1, 1),
('What is 21 ÷ 3?', LOWER(SHA2('7', 256)), 'Answer', 1, 1),
('What is 10 + 11?', LOWER(SHA2('21', 256)), 'Answer', 1, 1),
('What is 30 - 12?', LOWER(SHA2('18', 256)), 'Answer', 1, 1),
('What is 6 × 3?', LOWER(SHA2('18', 256)), 'Answer', 1, 1),
('What is 25 - 5?', LOWER(SHA2('20', 256)), 'Answer', 1, 1),
('What is 4 × 4?', LOWER(SHA2('16', 256)), 'Answer', 1, 1),
('What is 40 ÷ 8?', LOWER(SHA2('5', 256)), 'Answer', 1, 1),
('Type the word ''discipline'' in lowercase', LOWER(SHA2('discipline', 256)), 'd...', 1, 1),
('Type the word ''consistency'' backwards', LOWER(SHA2('ycnetsisnoc', 256)), 'y...', 1, 1),
('Type the word ''morning'' backwards', LOWER(SHA2('gninrom', 256)), 'g...', 1, 1),
('Type ''EARLY'' in lowercase', LOWER(SHA2('early', 256)), 'e...', 1, 1),
('Type ''habit'' in uppercase', LOWER(SHA2('habit', 256)), 'H...', 1, 1),
('Type ''focus'' in uppercase', LOWER(SHA2('focus', 256)), 'F...', 1, 1),
('What is the opposite of ''Cold''?', LOWER(SHA2('hot', 256)), 'h...', 1, 1),
('What is the opposite of ''Up''?', LOWER(SHA2('down', 256)), 'd...', 1, 1),
('What is the opposite of ''In''?', LOWER(SHA2('out', 256)), 'o...', 1, 1),
('What is the opposite of ''True''?', LOWER(SHA2('false', 256)), 'f...', 1, 1),
('What is the opposite of ''Open''?', LOWER(SHA2('closed', 256)), 'c...', 1, 1),
('Type the first 3 letters of ''Friday''', LOWER(SHA2('fri', 256)), 'f...', 1, 1),
('Type the first 3 letters of ''Saturday''', LOWER(SHA2('sat', 256)), 's...', 1, 1),
('Type the first 3 letters of ''Sunday''', LOWER(SHA2('sun', 256)), 's...', 1, 1),
('Type the last 3 letters of ''morning''', LOWER(SHA2('ing', 256)), 'i...', 1, 1),
('Type the last 3 letters of ''discipline''', LOWER(SHA2('ine', 256)), 'i...', 1, 1),
('What is 50 - 25?', LOWER(SHA2('25', 256)), 'Answer', 1, 1),
('What is 3 × 7?', LOWER(SHA2('21', 256)), 'Answer', 1, 1),
('What is 2 × 9?', LOWER(SHA2('18', 256)), 'Answer', 1, 1),
('What is 16 ÷ 4?', LOWER(SHA2('4', 256)), 'Answer', 1, 1),
('What is 45 ÷ 5?', LOWER(SHA2('9', 256)), 'Answer', 1, 1),
('Type the word ''awake''', LOWER(SHA2('awake', 256)), 'a...', 1, 1),
('Type the word ''alive''', LOWER(SHA2('alive', 256)), 'a...', 1, 1),
('Type the word ''alert''', LOWER(SHA2('alert', 256)), 'a...', 1, 1),
('Type the word ''energy''', LOWER(SHA2('energy', 256)), 'e...', 1, 1),
('Type the word ''growth''', LOWER(SHA2('growth', 256)), 'g...', 1, 1),
('Type ''I am awake'' without spaces', LOWER(SHA2('iamawake', 256)), 'i...', 1, 1),
('Type ''good morning'' without spaces', LOWER(SHA2('goodmorning', 256)), 'g...', 1, 1),
('Type ''wake up'' without spaces', LOWER(SHA2('wakeup', 256)), 'w...', 1, 1),
('What is the first letter of ''Discipline''?', LOWER(SHA2('d', 256)), 'd', 1, 1),
('What is the first letter of ''Morning''?', LOWER(SHA2('m', 256)), 'm', 1, 1),
('What is the first letter of ''Focus''?', LOWER(SHA2('f', 256)), 'f', 1, 1),
('What is the last letter of ''Habit''?', LOWER(SHA2('t', 256)), 't', 1, 1),
('What is the last letter of ''Early''?', LOWER(SHA2('y', 256)), 'y', 1, 1),
('Spell the number 5 in words', LOWER(SHA2('five', 256)), 'f...', 1, 1),
('Spell the number 9 in words', LOWER(SHA2('nine', 256)), 'n...', 1, 1),
('Spell the number 10 in words', LOWER(SHA2('ten', 256)), 't...', 1, 1),
('Spell the number 7 in words', LOWER(SHA2('seven', 256)), 's...', 1, 1),
('Spell the number 3 in words', LOWER(SHA2('three', 256)), 't...', 1, 1),
('What color is the sky on a clear day?', LOWER(SHA2('blue', 256)), 'b...', 1, 1),
('What color are leaves usually?', LOWER(SHA2('green', 256)), 'g...', 1, 1),
('What color is coal?', LOWER(SHA2('black', 256)), 'b...', 1, 1),
('What color is snow?', LOWER(SHA2('white', 256)), 'w...', 1, 1),
('What color is the sun usually drawn as?', LOWER(SHA2('yellow', 256)), 'y...', 1, 1),
('Type the word ''consistency''', LOWER(SHA2('consistency', 256)), 'c...', 1, 1),
('Type the word ''discipline'' without the letter ''i''', LOWER(SHA2('dscplne', 256)), 'd...', 1, 1),
('Type the word ''morning'' without the letter ''n''', LOWER(SHA2('morig', 256)), 'm...', 1, 1),
('Type the word ''habit'' twice', LOWER(SHA2('habithabit', 256)), 'h...', 1, 1),
('Type the word ''focus'' twice', LOWER(SHA2('focusfocus', 256)), 'f...', 1, 1),
('What day comes after Monday?', LOWER(SHA2('tuesday', 256)), 't...', 1, 1),
('What day comes before Sunday?', LOWER(SHA2('saturday', 256)), 's...', 1, 1),
('What month comes after January?', LOWER(SHA2('february', 256)), 'f...', 1, 1),
('What month comes before March?', LOWER(SHA2('february', 256)), 'f...', 1, 1),
('What month is the 12th month?', LOWER(SHA2('december', 256)), 'd...', 1, 1),
('How many minutes are in 1 hour?', LOWER(SHA2('60', 256)), 'Answer', 1, 1),
('How many hours are in a day?', LOWER(SHA2('24', 256)), 'Answer', 1, 1),
('How many days are in a week?', LOWER(SHA2('7', 256)), 'Answer', 1, 1),
('How many seconds are in a minute?', LOWER(SHA2('60', 256)), 'Answer', 1, 1),
('How many days are in January?', LOWER(SHA2('31', 256)), 'Answer', 1, 1),
('Type the reverse of ''early''', LOWER(SHA2('ylrae', 256)), 'y...', 1, 1),
('Type the reverse of ''habit''', LOWER(SHA2('tibah', 256)), 't...', 1, 1),
('Type the reverse of ''focus''', LOWER(SHA2('sucof', 256)), 's...', 1, 1),
('Type the reverse of ''awake''', LOWER(SHA2('ekawa', 256)), 'e...', 1, 1),
('Type the reverse of ''alert''', LOWER(SHA2('trela', 256)), 't...', 1, 1),
('What is 100 - 45?', LOWER(SHA2('55', 256)), 'Answer', 1, 1),
('What is 11 + 14?', LOWER(SHA2('25', 256)), 'Answer', 1, 1),
('What is 3 × 9?', LOWER(SHA2('27', 256)), 'Answer', 1, 1),
('What is 81 ÷ 9?', LOWER(SHA2('9', 256)), 'Answer', 1, 1),
('What is 64 ÷ 8?', LOWER(SHA2('8', 256)), 'Answer', 1, 1),
('Type the word ''present''', LOWER(SHA2('present', 256)), 'p...', 1, 1),
('Type the word ''today''', LOWER(SHA2('today', 256)), 't...', 1, 1),
('Type the word ''now''', LOWER(SHA2('now', 256)), 'n...', 1, 1),
('Type the word ''ready''', LOWER(SHA2('ready', 256)), 'r...', 1, 1),
('Type the word ''commit''', LOWER(SHA2('commit', 256)), 'c...', 1, 1),
('Type only the vowels from ''discipline''', LOWER(SHA2('iiie', 256)), 'i...', 1, 1),
('Type only the consonants from ''focus''', LOWER(SHA2('fcs', 256)), 'f...', 1, 1),
('Type only the vowels from ''awake''', LOWER(SHA2('aae', 256)), 'a...', 1, 1),
('Type the number 123 backwards', LOWER(SHA2('321', 256)), '3...', 1, 1),
('Type the number 908 backwards', LOWER(SHA2('809', 256)), '8...', 1, 1),
('Type ''yes'' in uppercase', LOWER(SHA2('yes', 256)), 'Y...', 1, 1),
('Type ''no'' in uppercase', LOWER(SHA2('no', 256)), 'N...', 1, 1),
('Type ''ok'' in uppercase', LOWER(SHA2('ok', 256)), 'O...', 1, 1),
('Type ''hello'' in uppercase', LOWER(SHA2('hello', 256)), 'H...', 1, 1),
('Type ''time'' in uppercase', LOWER(SHA2('time', 256)), 'T...', 1, 1),
('Type ''I will wake up'' without spaces', LOWER(SHA2('iwillwakeup', 256)), 'i...', 1, 1),
('Type ''good habits'' without spaces', LOWER(SHA2('goodhabits', 256)), 'g...', 1, 1),
('Type ''stay focused'' without spaces', LOWER(SHA2('stayfocused', 256)), 's...', 1, 1),
('Type ''early riser'' without spaces', LOWER(SHA2('earlyriser', 256)), 'e...', 1, 1),
('Type ''daily routine'' without spaces', LOWER(SHA2('dailyroutine', 256)), 'd...', 1, 1);
